sno=int(input('enter sno:'))
n=input('enter name:')
g=input('enter gender:')
gr=input('enter group:')
add=input('enter address:')
cell=int(input('enter ph.no:'))
print('sno=',sno)
print('Name:',n)
print('Gender:',g)
print('Group:',gr)
print('Address:',add)
print('Phone:',cell)
